### ISSUE TITLE
Support for 800W Alternator/Charger

### ISSUE THREAD

**Issue by jcam** [rabits/ha-ef-ble#35]
The 800W Alternator/Charger supports both discharging and charging from a vehicle/RV or just any off the shelf battery, but it will not automatically switch over to re-charge the battery when the power station is plugged in.

With HA and BLE support of Alternator/Charger, automation could auto switch the alternator-charger to recharge mode when the power station has AC and switch it back when AC goes away.

**Comment by jcam** [comment]
@GnoX got one for this too!

[charger_config_entry-ef_ble-01JYZPPPT949FYZWGGMBRP93R5.json](https://github.com/user-attachments/files/20973551/charger_config_entry-ef_ble-01JYZPPPT949FYZWGGMBRP93R5.json)

**Comment by jcam** [comment]
The app with newer firmware lets you separately configure the current to/from the external battery in amps, rather than a single value in watts.
This is useful because most batteries have current limits regardless of the voltage... My external battery for example is 100A continuous output but just 20A input. 20A and 24V is 480W, while 20A at 28V is 560W, and the alt/chg will automatically ramp up as the charge voltage increases.

Let me know if you need me to re-download the debugging data, in case that changed? I *think* i had already updated the firmware when I ran this, but I'm not 100% sure.

**Comment by GnoX** [comment]
That's interesting, I didn't see any way to set amps from the message structure. What I'll probably need here is for you to enable option `Log deserialized device update messages` which starts printing decoded messages into logs and observe what fields change when you change amps from the ecoflow app. I'll look if they modified message structures in the latest app version over the weekend.

**Comment by jcam** [comment]
Is the process for doing this logging relatively obvious? I don't remember seeing this log deserialized option, but I also wasn't digging.
Would I need to put the device on wifi so i can control it from the app at the same time as home assistant is monitoring it, or would i capture a log before and after?

**Comment by GnoX** [comment]
Should be this option.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/c498bb15-8265-4e73-be29-43727d933026" />

This will start spamming logs with raw messages in debug mode. 

> Would I need to put the device on wifi so i can control it from the app at the same time as home assistant is monitoring it, or would i capture a log before and after?

It should easier to match if you connect it to the app and HA at the same time as the value changes immediately both in the app and the logs. But the other way should also work, it's just about identifying what field changes after you send the command.

**Comment by jcam** [comment]
Within this parsed packet: 
`Packet(0x14, 0x21, 0xFE, 0x15, bytes.fromhex('0820b0061dcd0600000000900801d008f001dd08a403d43bb5100000a442e010e71be810b32ecd1a00000000d01a01d81a4fe01a02a82401a82500b52500009643d52500000cc2dd25000048448526000000008d260000000085270000`8c42`8d270000`7042`92270208029d2d00008c42a02d00ad2d00008c42b02d00'), 0x01, 0x00, 0x13, b'\xd8s\x00\x00', 0x00)`

The first highlighted/non-fixed-width section is the "Reverse Charge Current" in the app (currently set to 70a / 8c42)
The second highlighted/non-fixed-width section is the "Maximum Charging Current" in the app (currently set to 60a / 7042)
The current for both is adjustable between 10a and 70a in 1a increments.
Perhaps you understand what's up with the weird hex increments, they don't make sense to me. (only including some here because an exhaustive list would be exhausting)
8c42 -> 70a
7042 -> 60a
4842 -> 50a
2042 -> 40a
f041 -> 30a
a041 -> 20a
9841 -> 19a
9041 -> 18a
8841 -> 17a
8041 -> 16a
7041 -> 15a
6041 -> 14a
5041 -> 13a
4041 -> 12a
3041 -> 11a
2041 -> 10a

**Comment by GnoX** [comment]
I was using incorrect message type for parsing - I think I was looking at the older version of ecoflow app and that's why I couldn't find that message. With the correct message type, current is configurable, so it should now be working. I replaced the pre-release version again so let me know if it works.

**Comment by jcam** [comment]
I do see the charge current! That works. The Reverse Charge Current is still missing though.

Here are the configurable options in the app:

<img width="1080" height="1096" alt="Image" src="https://github.com/user-attachments/assets/f9130874-27ff-44ed-b084-d2275887cea3" />

**Comment by jcam** [comment]
Reverse charge current is now present and working!
Not sure if worth adding, but the above "emergency reverse charging" option seems to only be in the app, not in HA.

**Comment by GnoX** [comment]
It is easy to add now that I have the correct message typ, just thinking about usefulness of this option - we're not really going for feature completness in this integration as it's just making it harder to maintain. 
Though if you think it is useful, I'll gladly add it.

**Comment by jcam** [comment]
It isn't an option I'll end up using myself, so I'd be happy to skip it for now.

Thanks!

**Comment by jaydisc** [comment]
Hi, how can we access this build that can communicate with the Alternator Charger? Thank you!

**Comment by jcam** [comment]
@GnoX how do we get your updates into the main build?
@jaydisc you need to add [GnoX's repo](https://github.com/GnoX/ha-ef-ble/) to your HACS, then manually choose the latest in the 0.17.0-a series (currently a3)

**Comment by GnoX** [comment]
Hey, sorry, I was juggling between few requests and was on a 2 week vacation so I pushed this one back. As @jcam says, currently, there's a pre-release [v0.17.0-a.3](https://github.com/GnoX/ha-ef-ble/releases/tag/v0.17.0-a.3) in my repo - I'll release it  and create a MR in this repo over this weekend.

**Comment by jaydisc** [comment]
Looks amazing. Thank you!

**Comment by G0BMH-HA** [comment]
Thanks for all the work done to get the Alternator Charger support in place.

I have one issue and don't know if anyone else is seeing this, or whether it's my implementation. When switching the operating mode everything works except Battery Maintenance Mode. When switching to it I get "Failed to perform the action select/select_option. 'tuple' object cannot be interpreted as an integer". Any thoughts?

**Comment by GnoX** [comment]
Yup, can confirm, caused by a single comma :) Should work in [v0.17.0-a.4](https://github.com/GnoX/ha-ef-ble/releases/tag/v0.17.0-a.4)

**Comment by G0BMH-HA** [comment]
Superb! That's sorted it. :-)

**Comment by jaydisc** [comment]
Hi, I have also noticed one slight issue. EcoFlow have changed the precision of the Start Voltage over the years… initially just whole numbers, than 0.5 increments, and it now supports 0.1 increments. However, whenever I use HA to make the change to a floating value, the value is floor'd before applied, i.e. if I set the value to 12.9 using HA, the value gets changed and sent to the Alternator Charger as 12. Returning to the EcoFlow app to set it with greater precision works fine, and is then correctly reflected in HA.

**Comment by GnoX** [comment]
Hey, seems like I left conversion to int when I was changing some things. Pushed a fix to PR and released [v0.17.1](https://github.com/GnoX/ha-ef-ble/releases/tag/v0.17.1) in my fork.

**Comment by jaydisc** [comment]
> Hey, seems like I left conversion to int when I was changing some things. Pushed a fix to PR and released [v0.17.1](https://github.com/GnoX/ha-ef-ble/releases/tag/v0.17.1) in my fork.

Beautiful. Works as expected now.

**Comment by rabits** [comment]
Ok, just released as [v0.4.16](https://github.com/rabits/ha-ef-ble/releases/tag/v0.4.16), thank you @jcam, @jaydisc and @GnoX !
